### ISSUE TITLE
[SPIKE] The system must support the ability to update the Caikit serving runtime version without impacting actively served models

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/caikit-tgis-serving#11] opened 2023-07-12 20:49 UTC
From req doc:
For example, the upstream version will be updated and need to incorporate in RHODS as appropriate without impacting deployed models. A new RHODS release must not break model serving functionality.

**Comment by Xaenalt** [comment] 2023-07-13 14:50
Investigation needed into how KServe handles ServingRuntime updates. In general, when updating an InferenceService, a new deployment generation is created and a new ReplicaSet is spun up before spinning down the old one. This should handle the availability side of it with minimal downtime. That being said, updating the ServingRuntime may not affect all deployed pods in which case it's necessary to investigate how KServe handles it

**Comment by taneem-ibrahim** [comment] 2023-07-20 22:01
@Xaenalt 

> my reading is that it's more about updating the ServingRuntime side, determining what happens when the ServingRuntime gets updated

Correct. 

> is the intent for it to automatically restart all pods when a new ServingRuntime is rolled out, or just about the capability for us to update the ServingRuntime

Update serving runtime as part of the operator upgrade containing the updated runtime images and then automatically have the models be deployed with the new runtime (ie. restart of all pods).

**Comment by bdattoma** [comment] 2023-07-21 07:51
> have the models be deployed with the new runtime (ie. restart of all pods).


what about downtime in model availability? Do we accept that? Every pod once restarted must re-load the model.

**Comment by Xaenalt** [comment] 2023-07-24 13:23
We have to accept some downtime, though we can minimize it. As mentioned for large model downloads we will need to ensure that the new container doesn't present as "ready" until the model is available so that the deployment won't spin down the other container until the new one is serving the model.

There is one other consideration, potentially if the object storage connection has changed, that could present a problem, but there's no way to solve this since it would only happen due to user intervention

**Comment by Xaenalt** [comment] 2023-07-24 13:44
> > We have to accept some downtime, though we can minimize it. As mentioned for large model downloads we will need to ensure that the new container doesn't present as "ready" until the model is available so that the deployment won't spin down the other container until the new one is serving the model.
> 
> sounds fair. Maybe something for downstream, but is this accepted downtime considered as breaking SLA/SLO?

Good question, @taneem-ibrahim can you get us clarification on this point?

> 
> > There is one other consideration, potentially if the object storage connection has changed, that could present a problem, but there's no way to solve this since it would only happen due to user intervention
> 
> Not sure how much we can do for this case. If the object storage connection changes, user will need to change the Inference Service object too.

Agreed, just for awareness

**Comment by israel-hdez** [comment] 2023-07-24 14:31
> We have to accept some downtime, though we can minimize it. As mentioned for large model downloads we will need to ensure that the new container doesn't present as "ready" until the model is available so that the deployment won't spin down the other container until the new one is serving the model.

Remember that, in contrast with ModelMesh, there is a difference: the storage-initializer is an init-container. So, I think there are good chances that the pod won't present itself as ready until the storage initializer has finished pulling the model.

So, it is probably a matter about how much time it takes to load the model to memory.

**Comment by israel-hdez** [comment] 2023-09-20 20:58
This one seems to overlap a lot with opendatahub-io/kserve#40.

In a chat with Jeff, the outcome is that to upgrade a runtime, the recommended way is going to be to create a new `ServingRuntime` referring the updated image. Then, the user will need to change their `InferenceServices` to associate them with the new runtime.

IMHO, a RHODS update should follow that recommendation and any runtimes we ship out of the box should NOT be replacing previous versions, but should be creating new `ServingRuntime` resources. Then, it is going to be up to the user how and when to move to newer versions of the runtime. I personally think this is a very safe way to go, and updates won't be disruptive. 

If we go this way, maybe this spike is a "no-op".

**Comment by Xaenalt** [comment] 2023-09-21 04:41
Yep, agreed. Since we confirmed updating the ServingRuntime doesn't redeploy the ISVCs, I think that's an optimal approach to let the user schedule such updates. I think it'd be worth RH providing a script or something to do that update, but the approach is solid

**Comment by bdattoma** [comment] 2023-09-21 07:46
> we ship out of the box should NOT be replacing previous versions, but should be creating new ServingRuntime resources. Then, it is going to be up to the user how and when to move to newer versions of the runtime


What about cleaning the old versions? I guess when we will have UI it will be easily a task on the users to remove old ones. But if they pile up, it could be annoying for a user. 
Similarly, we support multiple versions of the notebook images and iirc the rule is that only version N-1 is supported. Is that correct? Should we have a similar rule here?

> I think it'd be worth RH providing a script or something to do that update, but the approach is solid


soon or later there will be a UI for KServe flow. So RH should provide the Upgrade funtionality from the UI

**Comment by Xaenalt** [comment] 2023-09-21 18:02
Yeah, let's say n-1 and also have a CLI option for these in our official docs and should be good

**Comment by israel-hdez** [comment] 2023-09-22 16:22
OK. I'll close this issue. Summary:

* A RHODS update should NOT replace existing `ServingRuntimes`. The update should create new `ServingRuntimes` for new versions of provided runtimes.
  * It is user responsibility to move `InferenceServices` to the new runtime, ensuring a smooth transition.
  * It is user responsibility to remove older unused runtimes.
* For a provided runtime, we only give support for the latest z-release in the _latest_ and _latest-1_ y-streams (this is tentative, we will formalize later).
* Docs should cover cleanup from UI and CLI.

**Closed by israel-hdez** 2023-09-22 16:22 UTC
Labels: good first issue, odh-release/1.8

**Comment by Xaenalt** [comment] 2023-09-22 16:26
Great summary!
